name: afq-insight-paper

channels:
  - conda-forge

dependencies:
  - python>=3.6
  - requests
  - jupyterlab
  - ipywidgets
  - numpy
  - matplotlib
  - palettable
  - bokeh
  - pip
  - pip:
    - dipy
    - fury
    - deepdish
    - pybeeswarm
    - "git+git://github.com/richford/AFQ-Insight.git#egg=afqinsight"
